export const URL = 'http://localhost:4000';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

export const POST_SIGNUP = 'POST_SIGNUP';
export const POST_SIGNUP_ERROR = 'POST_SIGNUP_ERROR';

export const GET_USER_PRODUCTS = 'GET_USER_PRODUCTS';
export const GET_USER_PRODUCTS_ERROR = 'GET_USER_PRODUCTS_ERROR';

export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';
export const GET_USER_COMMENTS_ERROR = 'GET_USER_COMMENTS_ERROR';

export const POST_CREATE_PRODUCT = 'POST_CREATE_PRODUCT';
export const POST_CREATE_PRODUCT_ERROR = 'POST_CREATE_PRODUCT_ERROR';

export const GET_USER_BOOKMARKS = 'GET_USER_BOOKMARKS';
export const GET_USER_BOOKMARKS_ERROR = 'GET_USER_BOOKMARKS_ERROR';

export const GET_USER_OFFERS = 'GET_USER_OFFERS';
export const GET_USER_OFFERS_ERROR = 'GET_USER_OFFERS_ERROR';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_ERROR = 'GET_PRODUCT_DETAILS_ERROR';

export const GET_PRODUCT_COMMENTS = 'GET_PRODUCT_COMMENTS';
export const GET_PRODUCT_COMMENTS_ERROR = 'GET_PRODUCT_COMMENTS_ERROR';

export const POST_BOOKMARKS = 'POST_BOOKMARKS';
export const POST_BOOKMARKS_ERROR = 'POST_BOOKMARKS_ERROR';

export const POST_COMMENTS = 'POST_COMMENTS';
export const POST_COMMENTS_ERROR = 'POST_COMMENTS_ERROR';

export const POST_OFFERS = 'POST_OFFERS';
export const POST_OFFERS_ERROR = 'POST_OFFERS_ERRORS';

export const GET_USERNAME = 'GET_USERNAME';
export const GET_USERNAME_ERROR = 'GET_USERNAME_ERROR';

export const GET_NUM_OF_PROD_SOLD = 'GET_NUM_OF_PROD_SOLD';
export const GET_NUM_OF_PROD_SOLD_ERROR = 'GET_NUM_OF_PROD_SOLD_ERROR';

export const GET_CATEGORY_HIGH_TRANS = 'GET_CATEGORY_HIGH_TRANS';
export const GET_CATEGORY_HIGH_TRANS_ERROR = 'GET_CATEGORY_HIGH_TRANS_ERROR';

export const GET_OFFER_RANGE_PROD = 'GET_OFFER_RANGE_PROD';
export const GET_OFFER_RANGE_PROD_ERROR = 'GET_OFFER_RANGE_PROD_ERROR';

export const ACCEPT_OFFER = 'ACCEPT_OFFER';
export const ACCEPT_OFFER_ERROR = 'ACCEPT_OFFER_ERROR';

export const GET_GIVEN_OFFERS = 'GET_GIVEN_OFFERS';
export const GET_GIVEN_OFFERS_ERROR = 'GET_GIVEN_OFFERS_ERROR';

export const RESCIND_OFFER = 'RESCIND_OFFER';
export const RESCIND_OFFER_ERROR = 'RESCIND_OFFER_ERROR';

export const ACCEPTED_OFFER_BUYER = 'ACCEPTED_OFFER_BUYER';
export const ACCEPTED_OFFER_BUYER_ERROR = 'ACCEPTED_OFFER_BUYER_ERROR';

export const ACCEPTED_OFFER_SELLER = 'ACCEPTED_OFFER_SELLER';
export const ACCEPTED_OFFER_SELLER_ERROR = 'ACCEPTED_OFFER_SELLER_ERROR';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_ERROR = 'GET_ALL_PRODUCTS_ERROR';

export const RESET_STORE = 'RESET_STORE';
